Title: Service

tabs:
  panneau:
    label: Panneau
    sections:
      infos:
        type: fields
        fields:
          resume:
            label: Résumé
            type: textarea
            size: small
            required: true
            help: "Apparaîtra sous le nom du service."
          horaires:
            label: Horaires
            type: structure
            fields:
              jour:
                label: Jour(s)
                type: text
                required: true
                help: "Format: Lundi / Lundi et Mardi / Lundi au Mardi"
              horaireDebutMatin:
                label: Horaire ouverture matin
                type: text
                help: "Format: Xh"
              horaireFinMatin:
                label: Horaire fermeture matin
                type: text
                help: "Format: Xh"
              horaireDebutAprem:
                label: Horaire ouverture après-midi
                type: text
                help: "Format: Xh"
              horaireFinAprem:
                label: Horaire fermeture après-midi
                type: text
                help: "Format: Xh"
            help: "Apparaîtra sous le résumé du service."
          telephone:
            label: Numéro(s) de téléphone
            type: structure
            fields:
              numero:
                label: Numéro
                type: tel
          mails:
            label: Mail(s) de contact
            type: structure
            fields:
              adresse:
                label: Adresse
                type: email
            required: true
            help: "Adresse(s) utilisée(s) pour le formulaire de contact."
  article:
    label: Article
    sections:
      partenaires:
        type: files
        parent: page.find('partenaires')
        layout: cards
      fichiers:
        type: files
        parent: page.find('fichiers')
        layout: list
        help: Glisser-déposer le fichier à télécharger dans le contenu pour y insérer son lien relatif.
      contenu:
        type: fields
        fields:
          contenu:
            label: Contenu
            type: blocks
            fieldsets:
              - heading
              - text
              - list
              - markdown
              - image