Title: Services

sections:
  published:
    headline: Pages publiées
    type: pages
    template: service
    status: published
    layout: list
    limit: 10
    image:
      cover: true
    help: "Liste apparaissant sur la page services."
  drafts:
    headline: Brouillons
    type: pages
    template: service
    status: drafts
    layout: list
    limit: 5