Title: Services

sections:
  services:
    headline: Services
    type: pages
    parent: site.find('services')
    templates: 
      - service
      - permanences-partenaires
    status: all
    layout: list
    limit: 10
    image:
      cover: true
    help: "Liste apparaissant sur la page services."