Title: Services

sections:
  published:
    headline: Pages publiées
    type: pages
    template: service
    # info: "Catégorie: {{ page.category }}"
    status: published
    layout: cards
    image:
      ratio: 1/1
      cover: true
  drafts:
    headline: Brouillons
    type: pages
    template: service
    # info: "Catégorie: {{ page.category }}"
    status: drafts
    layout: list
    limit: 5
    image:
      ratio: 1/1
      cover: true