tabs:
  site:
    label: Site
    columns:
      - width: 1/2
        sections:
          unlisted:
            headline: Pages publiées
            type: pages
            status: unlisted
            layout: list
            sortBy: title asc
            templates:
              - home
              - adhesion
              - contact
              - nous-trouver
              - mentions-legales
          listed:
            headline: Menu de navigation
            type: pages
            status: listed
            layout: list
          drafts:
            headline: Brouillons
            type: pages
            status: drafts
            layout: list
            limit: 5
            
      - width: 1/2
        sections:
          ticker:
            type: fields
            fields:
              breves:
                label: Ticker
                type: structure
                fields:
                  titre:
                    label: Titre
                    type: text
                    required: true
                  contenu:
                    label: Contenu
                    type: textarea
                    size: small
                    required: true
                help: "Chaque brève est constituée d'un titre et d'un texte court."
          slider:
            label: Slider
            type: files
            parent: site.children.find('actualites').find('slider')
            layout: cards
            image:
              ratio: 3/1
              cover: true
            help: "Images format bannière seulement."

  header:
    label: En-tête
    columns:
      - width: 1/2
        sections:
          logo:
            type: files
            parent: site.children.find('header').find('logo')
            layout: cards
      - width: 1/2
        sections:
          favicon:
            type: files
            parent: site.children.find('header').find('favicon')
            layout: cards

  footer:
    label: Pied de page
    columns:
      - width: 2/2
        sections:
          partenaires:
            type: files
            parent: site.children.find('footer')
            layout: cards
          infos:
            type: fields
            fields:
              nom:
                label: Nom
                type: text
                required: true
              adresse:
                label: Adresse
                type: textarea
                size: small
                required: true
              numero:
                label: Numéro de téléphone
                type: tel
                required: true
              facebook:
                label: Lien Facebook
                type: url
                required: true
              twitter:
                label: Lien Twitter
                type: url
                required: true
              instagram:
                label: Lien Instagram
                type: url
                required: true
              adhesion:
                label: Adhésion
                type: textarea
                size: small
                required: true
                help: "Ces informations apparaîtront en pied de page."