Title: Image

columns:
  - width: 1/2
    sections:
      alt:
        type: fields
        fields:
          alt:
            label: Alt
            type: text
  - width: 1/2
    sections:
      date:
        type: fields
        fields:
          toggle:
            label: Date de fin d'affichage
            type: toggle
            text: 
              - "non"
              - "oui"
            help: "Cette date affectera l'affichage des images du slider."
          dateFin:
            label: Date
            type: date
            display: DD/MM/YYYY
            when:
              toggle: true
            required: true